### ISSUE TITLE
How do I download manga files?

### ISSUE THREAD

**Issue by fromZahir2Aleph** [B-M-dev/Bilingual_Manga-home-#2]
I got to the step "You can use the website offline and read your downloaded manga by using this url http://0.0.0.0:3000 in any browser." of README. I can open the website, get to the manga page I need but it doesn't show any images of manga as I haven't downloaded any. How do I do that?

PS Thanks for the repo

**Comment by B-M-dev** [comment]
@fromZahir2Aleph download the entire website using this torrent https://github.com/B-M-dev/Bilingual_Manga_databases/blob/main/BilingualManga(feb112024).torrent
place the folders in B-M-home directory.I mean manga-covers,ocr ,wp-content and ipfs.
Extract the tar files in tar-ipfs to ipfs folder.
Importantly change the cdn and ipfsgate values to that of cdn1 and ipfsgate1 i.e bilingualmanga links are replaced to localhost links in manga-meta.json 
Hopefully this works.
You can also check the source code and maybe write a program to download only the chapters you want to read from the torrent.The ids can be found in manga_data.

**Comment by fromZahir2Aleph** [comment]
I have changed admin.manga_metadata.json settings to:
  "ipfsgate": "http://localhost:3300/ipfs/%@cid@%",
  "ipfsgate1": "http://localhost:3300/ipfs/%@cid@%",
  "cdn": "http://localhost:3300",
  "cdn1": "http://localhost:3300",

**Comment by fromZahir2Aleph** [comment]
![Screenshot_20240311_191822](https://github.com/B-M-dev/Bilingual_Manga-home-/assets/29507279/53747719-4be0-4c7b-857d-256295c943cb)

**Comment by fromZahir2Aleph** [comment]
Below are the contents of ipfs folder:

.:
bafybeigxz3a6fzbokealk5ejkhvtx2tf4saq4v7zboxfz3bfwlbp7l6jl4

./bafybeigxz3a6fzbokealk5ejkhvtx2tf4saq4v7zboxfz3bfwlbp7l6jl4:
853a686c9a298abf9217ecb6fc02213d

./bafybeigxz3a6fzbokealk5ejkhvtx2tf4saq4v7zboxfz3bfwlbp7l6jl4/853a686c9a298abf9217ecb6fc02213d:
Yotsubato_v01_000-a.jpg    Yotsubato_v01_015.jpg  Yotsubato_v01_035.jpg
Yotsubato_v01_000-b.jpg    Yotsubato_v01_016.jpg  Yotsubato_v01_036.jpg
Yotsubato_v01_000-c.jpg    Yotsubato_v01_017.jpg  Yotsubato_v01_037.jpg
Yotsubato_v01_000-d.jpg    Yotsubato_v01_018.jpg  Yotsubato_v01_038.jpg
Yotsubato_v01_000-e.jpg    Yotsubato_v01_019.jpg  Yotsubato_v01_039.jpg
Yotsubato_v01_000-f.jpg    Yotsubato_v01_020.jpg  Yotsubato_v01_040.jpg
Yotsubato_v01_000-g.jpg    Yotsubato_v01_021.jpg  Yotsubato_v01_041.jpg
Yotsubato_v01_001.jpg      Yotsubato_v01_022.jpg  Yotsubato_v01_042.jpg
Yotsubato_v01_002.jpg      Yotsubato_v01_023.jpg  Yotsubato_v01_043.jpg
Yotsubato_v01_003.jpg      Yotsubato_v01_024.jpg  Yotsubato_v01_044.jpg
Yotsubato_v01_004-005.jpg  Yotsubato_v01_025.jpg  Yotsubato_v01_045.jpg
Yotsubato_v01_006.jpg      Yotsubato_v01_026.jpg  Yotsubato_v01_046.jpg
Yotsubato_v01_007.jpg      Yotsubato_v01_027.jpg  Yotsubato_v01_047.jpg
Yotsubato_v01_008.jpg      Yotsubato_v01_028.jpg  Yotsubato_v01_048.jpg
Yotsubato_v01_009.jpg      Yotsubato_v01_029.jpg  Yotsubato_v01_049.jpg
Yotsubato_v01_010.jpg      Yotsubato_v01_030.jpg  Yotsubato_v01_050.jpg
Yotsubato_v01_011.jpg      Yotsubato_v01_031.jpg  Yotsubato_v01_051.jpg
Yotsubato_v01_012.jpg      Yotsubato_v01_032.jpg  Yotsubato_v01_052.jpg
Yotsubato_v01_013.jpg      Yotsubato_v01_033.jpg
Yotsubato_v01_014.jpg      Yotsubato_v01_034.jpg

**Comment by fromZahir2Aleph** [comment]
The browser window just flickers when I open the first volume of Yotsuba. The same for mangas I don't have in ipfs folder. Terminal doesn't show any errors. Where did I make a mistake?

**Comment by B-M-dev** [comment]
@fromZahir2Aleph You can only read the manga images in your ipfs folder that is the chapter with this cid bafybeigxz3a6fzbokealk5ejkhvtx2tf4saq4v7zboxfz3bfwlbp7l6jl4

**Comment by fromZahir2Aleph** [comment]
That's my intention atm. I wanna read the first chapter of Yotsuba.
I don't have space to download everything.

PS I noticed that I haven't extracted ocr. Still doesn't work after extraction.

**Comment by fromZahir2Aleph** [comment]
I have solved the problem by converting the ipfs files to html with manga-ocr. Still would be nice if this worked out of the box. Thanks for the files anyway. They are very much needed and appreciated!

**Comment by fromZahir2Aleph** [comment]
It works in Firefox!!! Must be some extension issues in my Chrome.

Thanks for the files again. They are very much needed and appreciated!

**Comment by tankoubon** [comment]
@fromZahir2Aleph @B-M-dev 
Hi,
just a heads up. [Here's a script](https://github.com/tankoubon/Bilingual-Manga-Downloader) to fetch only select titles without having to download the whole 700-800 GB archive. [There's also a fix here](https://github.com/tankoubon/Bilingual_Manga-home--src-) for the flickering when the volume/chapter is missing so it displays meaningful error message.

**Comment by fromZahir2Aleph** [comment]
> @fromZahir2Aleph @B-M-dev Hi, just a heads up. [Here's a script](https://github.com/tankoubon/Bilingual-Manga-Downloader) to fetch only select titles without having to download the whole 700-800 GB archive. [There's also a fix here](https://github.com/tankoubon/Bilingual_Manga-home--src-) for the flickering when the volume/chapter is missing so it displays meaningful error message.

You saved me a lot of time. Thanks!!

There is a mistake in your README. 'bm-qtb.py' instead of 'bm-qbt.py' . For a noob like me that can be quite a nuisance)
